name: Stock Monitor

on:
  schedule:
    # Run every 15 minutes (more reliable than every 5)
    - cron: '*/15 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
        
    - name: Check stock status
      env:
        MONITOR_URL: ${{ secrets.MONITOR_URL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python stock_monitor.py 